/*
  Warnings:

  - The primary key for the `Budgets` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - The primary key for the `Expense` table will be changed. If it partially fails, the table could be left without primary key constraint.

*/
-- AlterTable
ALTER TABLE "Budgets" DROP CONSTRAINT "Budgets_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE bigint,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "amount" SET DATA TYPE bigint,
ADD CONSTRAINT "Budgets_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "Expense" DROP CONSTRAINT "Expense_pkey",
ALTER COLUMN "id" SET DATA TYPE bigint,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "amount" SET DATA TYPE bigint,
ADD CONSTRAINT "Expense_pkey" PRIMARY KEY ("id");
